title: Homebrew Website Club, London
description: "Finish that blog post you’ve been working on. Demos of personal websites and technology. Discussion around the independent web. Join a community with like-minded interests. Bring friends that want a personal site!"
#root_url: http://127.0.0.1:4000
root_url: https://hwclondon.co.uk
collections:
  events:
    output: true
    permalink: /meetups/:path
defaults:
  - scope:
      path: ''
    values:
      layout: event
sass:
    sass_dir: _sass
    style: compressed
plugins:
  - jekyll-redirect-from
event: "Demos of personal websites and the opportunity to create, update or experiment on your personal website. Whether you're a coder, designer, or just someone who wants to improve their presence on the web, this meetup is for you."
upcoming: false