title: Homebrew Website Club, London
#root_url: http://127.0.0.1:4000
root_url: https://hwclondon.co.uk
collections:
  events:
    output: true
    permalink: /meetups/:path
defaults:
  - scope:
      path: ''
    values:
      layout: event
sass:
    sass_dir: _sass
    style: compressed
plugins:
  - jekyll-redirect-from
