title: Homebrew Website Club, London
root_url: https://hwclondon.co.uk
collections:
  events:
    output: true
    permalink: /:path
defaults:
  - scope:
      path: ''
    values:
      layout: event
